In [1]:
import numpy as np 
import tensorflow as tf
import os 
import sys 

import shap


    
def compute_data_metrics(classifier, input_data, input_adj, y_true):
    # Assuming the TensorFlow  is stored in the variable `model`
    y_train_pred = classifier.model.predict([input_data, input_adj])
    y_train_pred_argmax = np.argmax(y_train_pred, axis=1)
    y_train_true = np.argmax(y_true, axis=1)
    from utils.utils_mine import get_metrics
    return get_metrics(y_train_pred_argmax, y_train_true)

main_pth = '/home/jy/Documents/fnirs/treatment_response/fnirs-depression-deeplearning/'
sys.path.append(main_pth)
os.chdir(main_pth)
from LOO_nested_CV_model import build_model

def print_test_val_metrics(np_test_metrics, np_val_metrics):
    
    # np_test_metrics /= 100 
    # np_val_metrics /= 100
    
    mean_test_metrics = np.mean(np_test_metrics, axis=0)
    std_test_metrics = np.std(np_test_metrics, axis=0)

    mean_val_metrics = np.mean(np_val_metrics, axis=0)
    std_val_metrics = np.std(np_val_metrics, axis=0)
    
    from utils.fnirs_utils import print_md_table_val_test_AUC
    print_md_table_val_test_AUC('Mean', mean_test_metrics, mean_val_metrics, already_balanced_accuracy=False)
    print_md_table_val_test_AUC('STD', std_test_metrics, std_val_metrics, already_balanced_accuracy=False, print_table_header=False)
    
def save(test_metrics, val_metrics, y_pred_test_all, save_fold):

    np_test_metrics = np.array(test_metrics)
    np_test_metrics[:, 0] = (np_test_metrics[:, 1] + np_test_metrics[:, 0]) / 2
    print(np_test_metrics)
    np_val_metrics = np.array(val_metrics)
    np_val_metrics = np.reshape(np_val_metrics, (-1, 64, 5, 4))
    np_val_metrics = np.mean(np_val_metrics, axis=(1,2))
    np_val_metrics[:, 0] = (np_val_metrics[:, 1] + np_val_metrics[:, 2])/2
    np_y_pred_test_all = np.array(y_pred_test_all)


    print_test_val_metrics(np_test_metrics, np_val_metrics)

    # 
    if not os.path.exists(save_fold):
        os.makedirs(save_fold)
    np.save(save_fold + '/val_metrics.npy', np_val_metrics)
    np.save(save_fold + '/test_metrics.npy', np_test_metrics)
    np.save(save_fold + '/y_pred_test_all.npy', np_y_pred_test_all)    

model_name =  'gnn_transformer' # 'gnn_transformer_with_task_change_v2' 'gnn_transformer_with_cli_demo_v1'#'gnn_transformer_with_cli_demo' # 'gnn_transformer' gnn_transformer_with_task_change_v1
config_file_name = 'pretreatment_response_nor' # pretreatment_response_cv_5_mix_hb pretreatment_response_mamba
msg = 'loocv_v4to13'
TrainModel = build_model(model_name, config_file_name, msg)


2024-06-28 08:57:10.014770: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-28 08:57:10.034220: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:7704] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-28 08:57:10.034242: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-28 08:57:10.034250: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1520] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-28 08:57:10.038915: I tensorflow/core/platform/cpu_feature_g

fold_path is not founded yet results/gnn_transformer/prognosis_mix_hb/pretreatment_response/loocv_v4to13l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_classweight1_5/LOO_nested_CV/LOO_0/stratified_nested_5_CV_fold-0
results/gnn_transformer/prognosis_mix_hb/pretreatment_response/loocv_v4to13l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_classweight1_5/LOO_nested_CV/LOO_0/stratified_nested_5_CV_fold-0/val_acc.txt will be set to 0 because it has not been trained yet
fold_path is not founded yet results/gnn_transformer/prognosis_mix_hb/pretreatment_response/loocv_v4to13l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_classweight1_5/LOO_nested_CV/LOO_0/stratified_nested_5_CV_fold-1
results/gnn_transformer/prognosis_mix_hb/pretreatment_response/loocv_v4to13l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_classweight1_5/LOO_nested_CV/LOO_0/stratified_nested_5_CV_fold-1/val_acc.txt will be set to 0 because it has not been trained yet


2024-06-28 08:57:11.422594: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-28 08:57:11.422689: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-28 08:57:11.424276: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

X_train: (51, 52, 2500)
X_val: (12, 52, 2500)
X_test: (1, 52, 2500)
total sample size is 64
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_3 (InputLayer)        [(None, 52, 2500, 1)]        0         []                            
                                                                                                  
 tf.__operators__.getitem (  (None, 52, 2500)             0         ['input_3[0][0]']             
 SlicingOpLambda)                                                                                 
                                                                                                  
 input_1 (InputLayer)        [(None, 52, 52)]             0         []                            
                                                                                                  
 t

In [4]:
from utils.utils_mine import stratified_LOO_nested_CV

data = TrainModel.data
label = TrainModel.label
adj = TrainModel.adj
# if TrainModel.cli_demo.any():
#     cli_demo = TrainModel.cli_demo
# else:
#     cli_demo = None
    
current_loo = 0
k = 0
num_of_k_fold = 5
classifier = TrainModel.model
# X_train, Y_train, X_val, Y_val, X_test, Y_test, adj_train, adj_val, adj_test = stratified_LOO_nested_CV(data, label, k=k, num_of_k_fold=num_of_k_fold, current_loo=current_loo, adj=adj)

X_train, Y_train, X_val, Y_val, X_test, Y_test = stratified_LOO_nested_CV(data, label, k=k, num_of_k_fold=num_of_k_fold, current_loo=current_loo)

# print(f'X_train: {X_train.shape}')
# print(f'X_val: {X_val.shape}')
# print(f'X_test: {X_test.shape}')

label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]


In [6]:
from utils.fnirs_utils import get_metrics_auc

all_subjects_shap = []
val_metrics = []
test_metrics = []
y_pred_test_all = []
y_pred_val_all = []
# for v_i in range(4, 4+10):
for v_i in range(1): # loocv_v0l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_classweight1_5_epochs_1000
    model_para = f'loocv_v{v_i}pretreatment_response_nor'
    y_pred_test_fold = []
    for subject in range(64):
        for k_fold in range(num_of_k_fold):
            X_train, Y_train, X_val, Y_val, X_test, Y_test, adj_train, adj_val, adj_test = stratified_LOO_nested_CV(data, label, k=k_fold, num_of_k_fold=num_of_k_fold, current_loo=subject, adj=adj)
            checkpoint_path = f'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/checkpoint' # fold-best-checkpoint

            classifier.model.load_weights(checkpoint_path)
            model = classifier.model
            y_pred_val = model.predict([X_val, adj_val])
            y_pred_test = model.predict([X_test, adj_test])
            y_pred_test_fold.append(y_pred_test)
            val_metrics.append(get_metrics_auc(Y_val.argmax(axis=1), y_pred_val))
    y_pred_test_fold = np.array(y_pred_test_fold)
    y_pred_test_fold = np.squeeze(y_pred_test_fold)
    y_pred_test_fold = y_pred_test_fold.reshape(64, 5, 2)
    y_pred_test_fold = np.mean(y_pred_test_fold, axis=1)
    y_pred_test_all.append(y_pred_test_fold)
    test_metrics.append(get_metrics_auc(label.argmax(axis=1), y_pred_test_fold))
            # NOTE TO DO: why the train metrics are very bad? see sub-0 fold-0/1 
            # train_metrics = compute_data_metrics(classifier, X_train, adj_train, Y_train)
            # val_metrics = compute_data_metrics(classifier, X_val, adj_val, Y_val)
            # print(f"sub - {subject} - fold - {k_fold} - train metrics - {train_metrics}")
            # print(f"sub - {subject} - fold - {k_fold} - val metrics - {val_metrics}")
            
            # explainer = shap.GradientExplainer(classifier.model, [X_train, adj_train])
            # shap_values, _ = explainer.shap_values([X_test, adj_test])
            # all_subjects_shap.append(shap_values)

save_fold = 'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'

# save_fold = 'results/gnn_transformer_with_cli_demo_v1/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
save(test_metrics, val_metrics, y_pred_test_all, save_fold)


label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]
1/1 [==============================] - 0s 13ms/step
label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0

2024-06-28 08:58:09.236231: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]
1/1 [==============================] - 0s 12ms/step
label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0

In [ ]:

from utils.fnirs_utils import get_metrics_auc

all_subjects_shap = []
val_metrics = []
test_metrics = []
y_pred_test_all = []
y_pred_val_all = []
# for v_i in range(6):
y_test_prediction_prob = []
for v_i in range(10):
    
    model_para = f'loocv_v{v_i}l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_num_class_2_classweight1_25'
    y_pred_test_fold = []
    for subject in range(64):
        for k_fold in range(num_of_k_fold):
            X_train, Y_train, X_val, Y_val, X_test, Y_test, adj_train, adj_val, adj_test, cli_demo_train, cli_demo_val, cli_demo_test = stratified_LOO_nested_CV(data, label, k=k_fold, num_of_k_fold=num_of_k_fold, current_loo=subject, adj=adj, cli_demo=cli_demo)
            checkpoint_path = f'results/gnn_transformer_with_cli_demo_v1/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/checkpoint' # fold-best-checkpoint

            classifier.model.load_weights(checkpoint_path)
            model = classifier.model
            y_pred_val = model.predict([X_val, adj_val, cli_demo_val])
            y_pred_test = model.predict([X_test, adj_test, cli_demo_test])
            # y_test_prediction_prob.append(y_pred_test)
            y_test_prediction_prob.append(y_pred_test[0, 1])
            y_pred_test_fold.append(y_pred_test)
            val_metrics.append(get_metrics_auc(Y_val.argmax(axis=1), y_pred_val))
    y_pred_test_fold = np.array(y_pred_test_fold)
    y_pred_test_fold = np.squeeze(y_pred_test_fold)
    y_pred_test_fold = y_pred_test_fold.reshape(64, 5, 2)
    y_pred_test_fold = np.mean(y_pred_test_fold, axis=1)
    y_pred_test_all.append(y_pred_test_fold)
    test_metrics.append(get_metrics_auc(label.argmax(axis=1), y_pred_test_fold))
            # NOTE TO DO: why the train metrics are very bad? see sub-0 fold-0/1 
            # train_metrics = compute_data_metrics(classifier, X_train, adj_train, Y_train)
            # val_metrics = compute_data_metrics(classifier, X_val, adj_val, Y_val)
            # print(f"sub - {subject} - fold - {k_fold} - train metrics - {train_metrics}")
            # print(f"sub - {subject} - fold - {k_fold} - val metrics - {val_metrics}")
            
            # explainer = shap.GradientExplainer(classifier.model, [X_train, adj_train])
            # shap_values, _ = explainer.shap_values([X_test, adj_test])
            # all_subjects_shap.append(shap_values)

save_fold = 'results/gnn_transformer_with_cli_demo_v1/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
save(test_metrics, val_metrics, y_pred_test_all, save_fold)

In [ ]:

from utils.fnirs_utils import get_metrics_auc

all_subjects_shap = []
val_metrics = []
test_metrics = []
y_pred_test_all = []
y_pred_val_all = []
# for v_i in range(6):
y_test_prediction_prob = []
model_name = 'gnn_transformer_with_task_change_v2'
for v_i in range(5):
    
    model_para = f'loocv_v{v_i}pretreatment_response_cv_5_mix_hb_epoch_500'
    y_pred_test_fold = []
    for subject in range(64):
        for k_fold in range(num_of_k_fold):
            X_train, Y_train, X_val, Y_val, X_test, Y_test, adj_train, adj_val, adj_test, cli_demo_train, cli_demo_val, cli_demo_test = stratified_LOO_nested_CV(data, label, k=k_fold, num_of_k_fold=num_of_k_fold, current_loo=subject, adj=adj, cli_demo=cli_demo)
            checkpoint_path = f'results/{model_name}/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/checkpoint' # fold-best-checkpoint

            classifier.model.load_weights(checkpoint_path)
            model = classifier.model
            y_pred_val = model.predict([X_val, adj_val, cli_demo_val])
            y_pred_test = model.predict([X_test, adj_test, cli_demo_test])
            # y_test_prediction_prob.append(y_pred_test)
            y_test_prediction_prob.append(y_pred_test[0, 1])
            y_pred_test_fold.append(y_pred_test)
            val_metrics.append(get_metrics_auc(Y_val.argmax(axis=1), y_pred_val))
    y_pred_test_fold = np.array(y_pred_test_fold)
    y_pred_test_fold = np.squeeze(y_pred_test_fold)
    y_pred_test_fold = y_pred_test_fold.reshape(64, 5, 2)
    y_pred_test_fold = np.mean(y_pred_test_fold, axis=1)
    y_pred_test_all.append(y_pred_test_fold)
    test_metrics.append(get_metrics_auc(label.argmax(axis=1), y_pred_test_fold))
            # NOTE TO DO: why the train metrics are very bad? see sub-0 fold-0/1 
            # train_metrics = compute_data_metrics(classifier, X_train, adj_train, Y_train)
            # val_metrics = compute_data_metrics(classifier, X_val, adj_val, Y_val)
            # print(f"sub - {subject} - fold - {k_fold} - train metrics - {train_metrics}")
            # print(f"sub - {subject} - fold - {k_fold} - val metrics - {val_metrics}")
            
            # explainer = shap.GradientExplainer(classifier.model, [X_train, adj_train])
            # shap_values, _ = explainer.shap_values([X_test, adj_test])
            # all_subjects_shap.append(shap_values)

save_fold = f'results/{model_name}/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
save(test_metrics, val_metrics, y_pred_test_all, save_fold)

In [3]:

from utils.fnirs_utils import get_metrics_auc

all_subjects_shap = []
val_metrics = []
test_metrics = []
y_pred_test_all = []
y_pred_val_all = []
# for v_i in range(6):
y_test_prediction_prob = []
model_name = 'mamba'
for v_i in range(1):
    
    model_para = f'loocv_v{v_i}' + config_file_name
    y_pred_test_fold = []
    for subject in range(64):
        for k_fold in range(num_of_k_fold):
            X_train, Y_train, X_val, Y_val, X_test, Y_test = stratified_LOO_nested_CV(data, label, k=k_fold, num_of_k_fold=num_of_k_fold, current_loo=subject)
            checkpoint_path = f'results/{model_name}/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/fold-best-checkpoint' # fold-best-checkpoint

            classifier.model.load_weights(checkpoint_path)
            model = classifier.model
            y_pred_val = model.predict(X_val)
            y_pred_test = model.predict(X_test)
            # y_test_prediction_prob.append(y_pred_test)
            y_test_prediction_prob.append(y_pred_test[0, 1])
            y_pred_test_fold.append(y_pred_test)
            val_metrics.append(get_metrics_auc(Y_val.argmax(axis=1), y_pred_val))
    y_pred_test_fold = np.array(y_pred_test_fold)
    y_pred_test_fold = np.squeeze(y_pred_test_fold)
    y_pred_test_fold = y_pred_test_fold.reshape(64, 5, 2)
    y_pred_test_fold = np.mean(y_pred_test_fold, axis=1)
    y_pred_test_all.append(y_pred_test_fold)
    test_metrics.append(get_metrics_auc(label.argmax(axis=1), y_pred_test_fold))
            # NOTE TO DO: why the train metrics are very bad? see sub-0 fold-0/1 
            # train_metrics = compute_data_metrics(classifier, X_train, adj_train, Y_train)
            # val_metrics = compute_data_metrics(classifier, X_val, adj_val, Y_val)
            # print(f"sub - {subject} - fold - {k_fold} - train metrics - {train_metrics}")
            # print(f"sub - {subject} - fold - {k_fold} - val metrics - {val_metrics}")
            
            # explainer = shap.GradientExplainer(classifier.model, [X_train, adj_train])
            # shap_values, _ = explainer.shap_values([X_test, adj_test])
            # all_subjects_shap.append(shap_values)

save_fold = f'results/{model_name}/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
save(test_metrics, val_metrics, y_pred_test_all, save_fold)

label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]


2024-06-11 15:52:24.448554: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2024-06-11 15:52:24.449957: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x770b8a5241b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-06-11 15:52:24.449971: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 4090, Compute Capability 8.9
2024-06-11 15:52:24.531048: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:434] Loaded cuDNN version 8600


1/1 [==============================] - 0s 61ms/step


2024-06-11 15:52:24.878288: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.9
2024-06-11 15:52:24.878302: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2024-06-11 15:52:24.878332: W tensorflow/compiler/xla/stream_executor/gpu/redzone_allocator.cc:318] UNIMPLEMENTED: ptxas ptxas too old. Falling back to the driver to compile.
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2024-06-11 15:52:24.880550: W tensorflow/compiler/xla/service/gpu/buffer_comparator.cc:641] UNIMPLEMENTED: ptxas ptxas too old. Falling back to the driver to compile.
Relying on driver to perform ptx compilation. 
Setting XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda  or modifying $PATH can be used to set the location of ptxas
This message will only be logged once.
2024-06-11 15:52:24.900636: I ./te

label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]
1/1 [==============================] - 0s 11ms/step
label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0

: 

In [ ]:
# GNN_TR_cli_v2 
from utils.fnirs_utils import get_metrics_auc

all_subjects_shap = []
val_metrics = []
test_metrics = []
y_pred_test_all = []
y_pred_val_all = []
for v_i in range(6):
    model_para = f'loocv_v{v_i}l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_num_class_2'
    y_pred_test_fold = []
    for subject in range(64):
        for k_fold in range(num_of_k_fold):
            X_train, Y_train, X_val, Y_val, X_test, Y_test, adj_train, adj_val, adj_test, cli_demo_train, cli_demo_val, cli_demo_test = stratified_LOO_nested_CV(data, label, k=k_fold, num_of_k_fold=num_of_k_fold, current_loo=subject, adj=adj, cli_demo=cli_demo)
            checkpoint_path = f'results/gnn_transformer_with_cli_demo/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/fold-best-checkpoint'

            classifier.model.load_weights(checkpoint_path)
            model = classifier.model
            y_pred_val = model.predict([X_val, adj_val, cli_demo_val])
            y_pred_test = model.predict([X_test, adj_test, cli_demo_test])
            y_pred_test_fold.append(y_pred_test)
            val_metrics.append(get_metrics_auc(Y_val.argmax(axis=1), y_pred_val))
    y_pred_test_fold = np.array(y_pred_test_fold)
    y_pred_test_fold = np.squeeze(y_pred_test_fold)
    y_pred_test_fold = y_pred_test_fold.reshape(64, 5, 2)
    y_pred_test_fold = np.mean(y_pred_test_fold, axis=1)
    y_pred_test_all.append(y_pred_test_fold)
    test_metrics.append(get_metrics_auc(label.argmax(axis=1), y_pred_test_fold))
            # NOTE TO DO: why the train metrics are very bad? see sub-0 fold-0/1 
            # train_metrics = compute_data_metrics(classifier, X_train, adj_train, Y_train)
            # val_metrics = compute_data_metrics(classifier, X_val, adj_val, Y_val)
            # print(f"sub - {subject} - fold - {k_fold} - train metrics - {train_metrics}")
            # print(f"sub - {subject} - fold - {k_fold} - val metrics - {val_metrics}")
            
            # explainer = shap.GradientExplainer(classifier.model, [X_train, adj_train])
            # shap_values, _ = explainer.shap_values([X_test, adj_test])
            # all_subjects_shap.append(shap_values)


In [7]:
# save the y_pred_prob
y_test_prediction_prob = np.array(y_test_prediction_prob)

test_metrics.append(get_metrics_auc(label.argmax(axis=1), y_pred_test_fold))

5.0

In [8]:
np_test_metrics = np.array(test_metrics)
np_test_metrics[:, 0] = (np_test_metrics[:, 1] + np_test_metrics[:, 0]) / 2
print(np_test_metrics)
np_val_metrics = np.array(val_metrics)
np_val_metrics = np.reshape(np_val_metrics, (-1, 64, 5, 4))
np_val_metrics = np.mean(np_val_metrics, axis=(1,2))
np_val_metrics[:, 0] = (np_val_metrics[:, 1] + np_val_metrics[:, 2])/2
print(np_val_metrics.shape)
print(np_val_metrics)

print_test_val_metrics(np_test_metrics, np_val_metrics)


[[0.53385417 0.33333333 0.85714286 0.51020408]
 [0.52604167 0.33333333 0.83673469 0.59047619]
 [0.55364583 0.46666667 0.69387755 0.61904762]
 [0.51041667 0.33333333 0.79591837 0.55102041]
 [0.59270833 0.46666667 0.79591837 0.61360544]
 [0.49270833 0.26666667 0.85714286 0.53197279]
 [0.61614583 0.46666667 0.85714286 0.57006803]
 [0.54375    0.4        0.7755102  0.60680272]
 [0.55364583 0.46666667 0.69387755 0.58367347]
 [0.50260417 0.33333333 0.7755102  0.52244898]]
(10, 4)
[[0.73177083 0.56458333 0.89895833 0.67407407]
 [0.72638889 0.55416667 0.89861111 0.67361111]
 [0.73168403 0.56927083 0.89409722 0.67476852]
 [0.73263889 0.56666667 0.89861111 0.67453704]
 [0.72326389 0.55104167 0.89548611 0.65619213]
 [0.73914931 0.58385417 0.89444444 0.68055556]
 [0.72369792 0.55052083 0.896875   0.65804398]
 [0.72864583 0.56354167 0.89375    0.67164352]
 [0.740625   0.58854167 0.89270833 0.67829861]
 [0.7390625  0.58854167 0.88958333 0.68466435]]
| Model Name | Testing Set |             |        

In [4]:

save_fold = 'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'

# save_fold = 'results/gnn_transformer_with_cli_demo_v1/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
save(test_metrics, val_metrics, y_pred_test_all, save_fold)

[[0.4921875  0.3125     0.79166667 0.55208333]
 [0.5109375  0.35       0.81818182 0.58409091]
 [0.52796053 0.36842105 0.82222222 0.59532164]
 [0.6328125  0.5        0.86956522 0.68478261]
 [0.50260417 0.33333333 0.80434783 0.56884058]
 [0.50260417 0.33333333 0.80434783 0.56884058]
 [0.4703125  0.3        0.79545455 0.54772727]
 [0.47940341 0.31818182 0.80952381 0.56385281]
 [0.50260417 0.33333333 0.80434783 0.56884058]
 [0.54600694 0.38888889 0.82608696 0.60748792]]
| Model Name | Testing Set |             |             |             | Validation Set |             |             |             |
|------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
|            | Balanced Accuracy | Sensitivity | Specificity | AUC | Balanced Accuracy | Sensitivity | Specificity | AUC |
| Mean   | 51.6743  | 35.3799  | 81.4574  | 58.4187  | 74.8976  | 59.8542  | 89.9410  | 68.9097  |
| STD   | 4.3864  | 5.4735  | 2.1113  | 3.7771  | 

In [13]:
# save_fold = 'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
# save_fold = 'results/gnn_transformer_with_cli_demo_v1/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'
save_fold = 'results/gnn_transformer_with_task_change_v2/prognosis_mix_hb/pretreatment_response/ten-fold-evaluate'

reload_test_metrics = np.load(save_fold + '/test_metrics.npy')
reload_val_metrics = np.load(save_fold + '/val_metrics.npy')
reload_y_pred_test_all = np.load(save_fold + '/y_pred_test_all.npy')
print(reload_test_metrics)
print('-'*10)
print(reload_val_metrics)


print_test_val_metrics(reload_test_metrics, reload_val_metrics)
print(f'This is result of {model_name}')

[[0.00706771 0.00866667 0.0044898  0.00721088]
 [0.00510938 0.006      0.00367347 0.00594558]
 [0.00595313 0.008      0.00265306 0.00589116]
 [0.00415104 0.00533333 0.0022449  0.00423129]
 [0.00477604 0.00533333 0.00387755 0.00531973]]
----------
[[0.00629427 0.00702604 0.0055625  0.00574942]
 [0.00622135 0.00681771 0.005625   0.00573264]
 [0.00650434 0.00736979 0.00563889 0.00593171]
 [0.00636285 0.00713542 0.00559028 0.00571296]
 [0.00634375 0.00729167 0.00539583 0.00571412]]
| Model Name | Testing Set |             |             |             | Validation Set |             |             |             |
|------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
|            | Balanced Accuracy | Sensitivity | Specificity | AUC | Balanced Accuracy | Sensitivity | Specificity | AUC |
| Mean   | 0.5027  | 0.6667  | 0.3388  | 0.5720  | 0.6345  | 0.7128  | 0.5562  | 0.5768  |
| STD   | 0.1110  | 0.1398  | 0.0822  | 0.0967

In [5]:
# this will be v_1 gnn_cli_tr

np_v1_gnntr_cli_test = np.array([
    [0.5671875, 0.4, 0.83673469, 0.61836735],
    [0.546875, 0.375, 0.83333333, 0.60416667],
    [0.61358173, 0.46153846, 0.84313725, 0.65233786],
    [0.58928571, 0.42857143, 0.84, 0.63428571],
    [0.51041667, 0.33333333, 0.82608696, 0.57971014],
    [0.57306985, 0.41176471, 0.85106383, 0.63141427],
    [0.52803309, 0.35294118, 0.82978723, 0.59136421],
    [0.61614583, 0.46666667, 0.85714286, 0.66190476],
    [0.640625, 0.5, 0.84615385, 0.67307692],
    [0.546875, 0.375, 0.83333333, 0.60416667]
])

np_v1_gnntr_cli_val = np.array([
    [0.75776042, 0.590625, 0.92489583, 0.69565972],
    [0.75340278, 0.584375, 0.92243056, 0.69706597],
    [0.75293403, 0.578125, 0.92774306, 0.70366319],
    [0.75595486, 0.590625, 0.92128472, 0.71010417],
    [0.76105903, 0.596875, 0.92524306, 0.71980903],
    [0.7490625, 0.5671875, 0.9309375, 0.69829861],
    [0.75142361, 0.571875, 0.93097222, 0.71489583],
    [0.75829861, 0.5859375, 0.93065972, 0.70935764],
    [0.75923611, 0.59375, 0.92472222, 0.72203125],
    [0.74357639, 0.55625, 0.93090278, 0.70305556]
])


print_test_val_metrics(np_v1_gnntr_cli_test, np_v1_gnntr_cli_val)


| Model Name | Testing Set |             |             |             | Validation Set |             |             |             |
|------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
|            | Balanced Accuracy | Sensitivity | Specificity | AUC | Balanced Accuracy | Sensitivity | Specificity | AUC |
| Mean   | 57.3210  | 41.0482  | 83.9677  | 62.5079  | 75.4271  | 58.1563  | 92.6979  | 70.7394  |
| STD   | 3.9603  | 5.0987  | 0.9276  | 2.9398  | 0.5041  | 1.2359  | 0.3560  | 0.8920  |


In [4]:
all_subjects_shap = np.array(all_subjects_shap)
print(all_subjects_shap.shape)
np.save('results/gnn_transformer/prognosis_mix_hb/pretreatment_response/loocv_v1l1_rate_0.01_l2_rate_0.01_d_model_16_batch_size_64_n_layers_6/LOO_nested_CV/shap.npy', all_subjects_shap)



(0,)


In [3]:
for v_i in range(10):
    model_para = f'loocv_v{v_i}l1_rate_0.01_l2_rate_0.001_d_model_16_batch_size_64_n_layers_6_classweight1_5_epochs_1000'
    all_subjects_shap_test = []
    all_subjects_shap_val = []
    for subject in range(64):
        for k_fold in range(num_of_k_fold):
            X_train, Y_train, X_val, Y_val, X_test, Y_test, adj_train, adj_val, adj_test = stratified_LOO_nested_CV(data, label, k=k_fold, num_of_k_fold=num_of_k_fold, current_loo=subject, adj=adj)
            X_train = X_train[..., np.newaxis]
            X_test = X_test[..., np.newaxis]
            X_val = X_val[..., np.newaxis]
            # checkpoint_path = f'results/gnn_transformer/prognosis/pretreatment_response/loocv_v1l1_rate_0.01_l2_rate_0.01_d_model_16_batch_size_64_n_layers_6/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/fold-best-checkpoint'
            checkpoint_path = f'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/LOO_{subject}/stratified_nested_5_CV_fold-{k_fold}/checkpoint'
            classifier.model.load_weights(checkpoint_path)

            
            # NOTE TO DO: why the train metrics are very bad? see sub-0 fold-0/1 
            # train_metrics = compute_data_metrics(classifier, X_train, adj_train, Y_train)
            # val_metrics = compute_data_metrics(classifier, X_val, adj_val, Y_val)
            # print(f"sub - {subject} - fold - {k_fold} - train metrics - {train_metrics}")
            # print(f"sub - {subject} - fold - {k_fold} - val metrics - {val_metrics}")
            
            
            
            explainer = shap.GradientExplainer(classifier.model, [X_train, adj_train])
            shap_values_test, _ = explainer.shap_values([X_test, adj_test])
            shap_values_val, _ = explainer.shap_values([X_val, adj_val])
            all_subjects_shap_test.append(shap_values_test)
            all_subjects_shap_val.append(shap_values_val)
    np.save(f'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/shap_test.npy', all_subjects_shap_test)
    np.save(f'results/gnn_transformer/prognosis_mix_hb/pretreatment_response/{model_para}/LOO_nested_CV/shap_val.npy', all_subjects_shap_val)


label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]


2024-06-04 13:02:31.705964: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
`tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.


label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
np.unique(label) [0 1]
label_not_onehot: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]
label: [[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


ValueError: could not broadcast input array from shape (52,2500,1) into shape (1,52)

In [22]:
all_shap = np.concatenate((shap_52, shap_last_12), axis=0)

In [20]:
shap_values_v1 = all_shap.copy()
print(shap_values_v1.shape)

shap_values_v1 = np.squeeze(shap_values_v1)
shap_values_v1 = np.mean(shap_values_v1, axis=0)[..., 1]
print(shap_values_v1.shape)


(320, 1, 52, 2500, 1, 2)
(52, 2500)


In [13]:
np.save('/home/jy/Documents/fnirs/treatment_response/fnirs-depression-deeplearning/results/gnn_transformer/prognosis_mix_hb/pretreatment_response/loocv_v2l1_rate_0.01_l2_rate_0.01_d_model_16_batch_size_64_n_layers_6/LOO_nested_CV/shap_0-52.npy', np.array(tmp))