In [1]:
import tensorflow as tf



In [12]:
x_1 = tf.ones((2,2))
# Define the indices to update and the new values for those indices
indices = [[0, 1]]  # The index to update
updates = [0]  # The new value to insert
x_1_updated = tf.tensor_scatter_nd_update(x_1, indices, updates)
print('original x_1', x_1_updated)

check_mask = tf.cast(tf.equal(x_1_updated, 0), tf.float32)
print('check_mask', check_mask)

x_1_updated -= 1 
print(x_1_updated)

large_negative = tf.fill([2, 2], -1e9)  # [[9, 9], [9, 9]]

print(x)

mask = x_1_updated * large_negative

print(mask)

original x_1 tf.Tensor(
[[1. 0.]
 [1. 1.]], shape=(2, 2), dtype=float32)
check_mask tf.Tensor(
[[0. 1.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0. -1.]
 [ 0.  0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.e+09 -1.e+09]
 [-1.e+09 -1.e+09]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.e+00  1.e+09]
 [-0.e+00 -0.e+00]], shape=(2, 2), dtype=float32)
