In [17]:

import tensorflow as tf
import numpy as np 
import matplotlib.pyplot as plt 

a = list(range(1, 11))
b = [a.copy() for i in range(10)]
b = np.array(b)
for i in range(10):
    b[i] = b[i] * (i+1)
print(b)
b_reduce_sum = np.sum(b, axis=-1)
print(f'b_reduce_sum: {b_reduce_sum}')
b_sqrt_inv = np.power(b_reduce_sum, -0.5)
b_sqrt_inv = np.linalg.diag(b_sqrt_inv)
print(f'b_sqrt_inv: {b_sqrt_inv}')
nor_b = np.matmul(np.matmul(b_sqrt_inv, b),b_sqrt_inv)
print(f'nor_b: {nor_b}')

def normalize_adjacency(adj):
    d = tf.reduce_sum(adj, axis=-1)
    d_sqrt_inv = tf.pow(d, -0.5)
    d_sqrt_inv = tf.where(tf.math.is_inf(d_sqrt_inv), 0., d_sqrt_inv)
    d_mat_inv_sqrt = tf.linalg.diag(d_sqrt_inv)
    return tf.matmul(tf.matmul(d_mat_inv_sqrt, adj), d_mat_inv_sqrt)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
b_reduce_sum: [ 55 110 165 220 275 330 385 440 495 550]


AttributeError: module 'numpy.linalg' has no attribute 'diag'

In [27]:
x = np.array([1,2,3]) 
x = x[np.newaxis, ...]
y = np.array([[1],[2],[3]])
# z = np.outer(x, x)
z = y @ x
print(z)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
